### ISSUE TITLE
Inconsistency with 'parse("13:00")' depending if Pendulum is built with C extensions or not

### ISSUE THREAD

**Issue by Delgan** [sdispater/pendulum#210]
Hi.

I made some tests with two different installations of Pendulum v2.0.1

_First one (Windows)_
```python
>>> import pendulum
>>> pendulum.parse("13:00")
DateTime(2018, 5, 15, 13, 0, 0, tzinfo=Timezone('UTC'))
```

_Second one (Linux)_
```python
>>> import pendulum
>>> pendulum.parse("13:00")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/delgan/env/lib/python3.6/site-packages/pendulum/parser.py", line 20, in parse
    return _parse(text, **options)
  File "/mnt/c/Users/delgan/env/lib/python3.6/site-packages/pendulum/parser.py", line 36, in _parse
    parsed = base_parse(text, **options)
  File "/mnt/c/Users/delgan/env/lib/python3.6/site-packages/pendulum/parsing/__init__.py", line 64, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/mnt/c/Users/delgan/env/lib/python3.6/site-packages/pendulum/parsing/__init__.py", line 116, in _parse
    raise ParserError('Unable to parse string [{}]'.format(text))
pendulum.parsing.exceptions.ParserError: Unable to parse string [13:00]
```

I guess this is somehow related to C extensions, because `from pendulum.parsing._iso8601 import parse_iso8601` raises a `ModuleNotFound` exception on my Windows, but not on Linux.

On the other hand, `from pendulum._extensions._helpers import local_time` works fine on both Linux and Windows, so it confuses me a little bit... 😕

**Comment by sdispater** [comment]
This should be fixed in the latest release: `2.0.2`

**Comment by Delgan** [comment]
@sdispater Thanks for the fix!

However, there is still a problem with `pendulum.parse("13")` which raises an exception, but shouldn't.
