### ISSUE TITLE
Parsing issue

### ISSUE THREAD

**Issue by guyzmo** [sdispater/pendulum#42]
Still on that Debian Wheezy (old-stable), I get a strange behaviour:

``` python
 % python3
Python 3.2.3 (default, Feb 20 2013, 17:02:41) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pendulum
>>> pendulum.parse('2016-09-04T15:30:09+02:00')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.2/dist-packages/pendulum/pendulum.py", line 242, in parse
    tzinfo=tz
  File "/usr/local/lib/python3.2/dist-packages/pendulum/pendulum.py", line 184, in __init__
    hour, minute, second, microsecond
  File "/usr/local/lib/python3.2/dist-packages/pendulum/tz/timezone.py", line 80, in convert
    return dt.__class__(*converted)
ValueError: day is out of range for month
>>> 
 % python
Python 2.7.3 (default, Jun 20 2016, 16:18:47) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pendulum
>>> pendulum.parse('2016-09-04T15:30:09+02:00')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pendulum/pendulum.py", line 242, in parse
    tzinfo=tz
  File "/usr/local/lib/python2.7/dist-packages/pendulum/pendulum.py", line 184, in __init__
    hour, minute, second, microsecond
  File "/usr/local/lib/python2.7/dist-packages/pendulum/tz/timezone.py", line 80, in convert
    return dt.__class__(*converted)
ValueError: day is out of range for month
>>> 
```

This is a quite weird behaviour, on *BOTH* python versions. Obviously, exact same code works fine on another computer running python3.5 and debian jessie.

**Comment by guyzmo** [comment]
I have launched my pdb at it, and here's a few insights.

I've setup a breakpoint within `__init__()` at the second step of the backtrace, and followed the code path, up until I see something fishy.

I opened my python REPL, and typed in:

``` python
>>> import pendulum
>>> pendulum.parse('2016-09-04T15:30:09+02:00')
```

I found something that smelled wrong in `tz.timezone` at line 191:

``` python
    def _to_local_time(self, unix_time, transition_type):
        local_time = _local_time(
            unix_time,
            transition_type
        )
```

where `unix_time` is `1472995809.0` and transition_type is `<TransitionType [7200, False, ]>`. But the result stored in `local_time` is:

``` python
(700, 1, -16196, 22, 47, 29, 0, 7200, False, '')
```

which does not make much sense to me. Finally, the `_to_local_time()` function returns:

``` python
>>> local_time[:7] + (tzinfo,)
(700, 1, -16196, 22, 47, 29, 0, <TimezoneInfo [+02:00, 7200, False]>)
```

that tuple is then returned to the `convert()` method of the `tz.timezone` module, and thrown at `datetime.datetime` with the following:

```
return dt.__class__(*converted)
```

but obviously, `-16196` makes a pretty bad day of month…

I'm not sure why pdb stepped over _local_time, but I'm adding a breakpoint within it to see WTH is going on in there to mess it up so much.

**Comment by guyzmo** [comment]
ok, so it looks like the issue comes from the `cbreakdown.so` module, within the C code. What are the chances it's a bloody optimisation or wrong flag, or maybe gcc bug?

The debian wheezy is running gcc 4.7.2.

**Comment by guyzmo** [comment]
yup, if I switch to the python implementation (by moving away `cbreakdown.so` from the site-packages), it works fine. It should be interesting to throw gdb at it…

**Comment by sdispater** [comment]
Thanks for the thorough debugging :-)

I can't reproduce on Arch Linux , Python 2.7.10 and gcc 6.1.1.

Could you install pendulum from the `develop` branch:

`pip install git+https://github.com/sdispater/pendulum.git@develop#egg=pendulum -U`

I changed the C extension from a Cython generated C code to a pure C extension, so maybe it will fix the issue.

**Comment by guyzmo** [comment]
I uninstalled and reinstalled it from both python version, and it's working… Though in `_extensions/tz` I see `_local_time.c` but no `.so` module, so I think it's falling back to the pure python implementation.

**Comment by sdispater** [comment]
Yes. If no .so file is present the compilation must have failed.

**Comment by guyzmo** [comment]
oh, looking more closely at the pip output:

```
    gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -fPIC -I/usr/include/python3.2mu -c pendulum/_extensions/tz/_local_time.c -o build/temp.linux-i686-3.2/pendulum/_extensions/tz/_local_time.o -Wno-unused-function
    pendulum/_extensions/tz/_local_time.c:23:1: error: initializer element is not constant
    pendulum/_extensions/tz/_local_time.c:24:1: error: initializer element is not constant
    pendulum/_extensions/tz/_local_time.c:28:1: error: initializer element is not constant
    pendulum/_extensions/tz/_local_time.c:33:5: error: initializer element is not constant
    pendulum/_extensions/tz/_local_time.c:33:5: error: (near initialization for ‘SECS_PER_100_YEARS[0]’)
    pendulum/_extensions/tz/_local_time.c:35:1: error: initializer element is not constant
    pendulum/_extensions/tz/_local_time.c:35:1: error: (near initialization for ‘SECS_PER_100_YEARS[1]’)
    pendulum/_extensions/tz/_local_time.c:40:5: error: initializer element is not constant
    pendulum/_extensions/tz/_local_time.c:40:5: error: (near initialization for ‘SECS_PER_4_YEARS[0]’)
    pendulum/_extensions/tz/_local_time.c:42:1: error: initializer element is not constant
    pendulum/_extensions/tz/_local_time.c:42:1: error: (near initialization for ‘SECS_PER_4_YEARS[1]’)
    pendulum/_extensions/tz/_local_time.c:46:5: error: initializer element is not constant
    pendulum/_extensions/tz/_local_time.c:46:5: error: (near initialization for ‘SECS_PER_YEAR[0]’)
    pendulum/_extensions/tz/_local_time.c:48:1: error: initializer element is not constant
    pendulum/_extensions/tz/_local_time.c:48:1: error: (near initialization for ‘SECS_PER_YEAR[1]’)
    ************************************************************
    Cannot compile C accelerator module, use pure python version
    ************************************************************
```

**Comment by guyzmo** [comment]
looks like gcc 4.7 is a pain ☺

**Comment by guyzmo** [comment]
so choices are:

- use preprocessor constant for all that,
- use constants definition like `60 * 60` instead of `60 * SECS_PER_MIN`
- say you don't support gcc

**Comment by sdispater** [comment]
I will fix this. Should not take too long :-)

**Comment by sdispater** [comment]
I just pushed a fix on the develop branch. It should build properly.

**Comment by guyzmo** [comment]
ok, it's building correctly, but I'm still having that same error :-/

**Comment by sdispater** [comment]
It must be a problem with you version of gcc then. I don't see another reason.

**Comment by sdispater** [comment]
But, what I don't understand is why it would work only for python 3.5.

**Comment by guyzmo** [comment]
no, it's not working as well for python 3.5, both `.so` are failing. So, yes, I believe as well it's an issue with my old gcc-4.7 on that server.

**Comment by guyzmo** [comment]
are you on a chat (IRC, gitter, slack, XMPP, whatever), so we can debunk more informally? I'm zmo on freenode.

**Comment by sdispater** [comment]
I just created a Slack team, so I can add it if you want.

**Comment by guyzmo** [comment]
ok, can you send me an invite to z+slack+python+pendulum@m0g.net ? I'll delete this commente as soon as I receive it ☺

**Comment by sdispater** [comment]
I just sent you an invitation.
